config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
    ActiveAdmin.routes(self)
  end

  devise_for :users, controllers: { registrations: 'users/registrations' }

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :forms do
        resources :results, only: [:index]
      end
    end
  end

  # health check endpoint
  get '/health', to: proc {[200, {}, ['ok']]}

  # public form routes
  get '/embed', to: 'public_form#embed', as: 'embed_js'
  get '/f/:id', to: 'public_form#show', as: 'public_form'
  get '/f/:id/embed', to: 'public_form#show', defaults: { embed: true }, as: 'public_form_embed'
  post '/f/:id', to: 'public_form#submit', defaults: { format: :json }

  # result endpoint
  get '/r/:id', to: 'result#show', as: 'result'

  # subscriptions
  resources :subscriptions, only: [:index] do
    collection do
      get '/confirm/:plan', to: 'subscriptions#confirm', as: 'confirm'
    end
  end

  namespace :stripe, path: '/subscription' do
    post '/', to: 'subscription#create', as: 'create_subscription'
    put '/', to: 'subscription#update', as: 'update_subscription'
    delete '/', to: 'subscription#destroy', as: 'destroy_subscription'
    post '/webhook', to: 'subscription#webhook', as: 'subscription_webhook'
  end

  # pages
  get '/contact', to: 'contact#index', as: 'contact'

  # catch every other request and send it to our react app
  get '*anything', to: 'dashboard#index',
    constraints: lambda { |req|
      # exclude XHR requests
      return false if req.xhr?

      # exclude non-html requests
      return false unless req.format.html?

      # exclude any engine routes manually (e.g. sidekiq)
      req.path.exclude?('/sidekiq')
    }

  authenticated :user do
    root to: 'dashboard#index', as: 'dashboard'
  end

  root 'welcome#index'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index; end
end

app/views/layouts/welcome/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class="columns formsling-footer">
      <div class="column is-5 is-marginless has-text-centered-mobile content has-text-grey">
        <p>Copyright © <%= Time.now.year %> FormSling. All rights reserved.</p>
      </div>
      <div class="column is-7">
        <ul class="columns formsling-bottom-links is-mobile is-multiline is-marginless">
          <li class="formsling-bottom-link">
            <%= link_to 'Contact Us', contact_path %>
          </li>
          <li class="formsling-bottom-link">
            <%= link_to('Sign Up', new_user_registration_path) %>
          </li>
          <li class="formsling-bottom-link">
            <% if user_signed_in? %>
            <%= link_to('Logout', destroy_user_session_path, method: :delete, class: 'navbar-item') %>
            <% else %>
            <%= link_to('Sign In', new_user_session_path) %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/welcome/_nav.html.erb
<nav class="navbar container formsling-main-nav" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <%= link_to root_path, class: 'navbar-item' do %>
    <%= image_tag asset_pack_path('media/images/formsling-logo-black.svg'), alt: "formsling", class: "nav-logo" %>
    <span class="nav-logo-text">ormSling</span>
    <% end %>

    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>
  <div class="navbar-menu" id="mainNavMenu">
    <div class="navbar-end has-text-info">
      <% unless user_signed_in? %>
      <%= link_to 'Features', root_path(anchor: 'features'), class: 'navbar-item' %>
      <%= link_to 'Pricing', root_path(anchor: 'pricing'), class: 'navbar-item' %>
      <%= link_to 'FAQ', root_path(anchor: 'faq'), class: 'navbar-item' %>
      <%= link_to 'Contact', contact_path, class: 'navbar-item' %>
      <%= link_to('Sign In', new_user_session_path, class: 'navbar-item') %>
      <% end %>
      <% if user_signed_in? && current_user.admin? %>
      <%= link_to 'ActiveAdmin', admin_root_path, target: '_blank', class: 'navbar-item' %>
      <%= link_to 'Sidekiq', sidekiq_web_path, target: '_blank', class: 'navbar-item' %>
      <% end %>

      <% if user_signed_in? %>
      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          <%= current_user.full_name %>
        </a>

        <div class="navbar-dropdown">
          <%= link_to 'View Your Forms', root_path, class: 'navbar-item' %>
          <%= link_to 'Manage Account', edit_user_registration_path, class: 'navbar-item' %>
          <hr class="navbar-divider">
          <%= link_to 'Contact', contact_path, class: 'navbar-item' %>
          <%= link_to('Logout', destroy_user_session_path, method: :delete, class: 'navbar-item') %>
        </div>
      </div>
      <% else %>
      <%= link_to('Sign Up', new_user_session_path, class: 'navbar-item formsling-main-nav--signup') %>
      <% end %>
    </div>
</nav>