config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
    ActiveAdmin.routes(self)
  end

  devise_for :users, controllers: { registrations: 'users/registrations' }

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :forms do
        resources :results, only: [:index]
      end
    end
  end

  # health check endpoint
  get '/health', to: proc {[200, {}, ['ok']]}

  # public form routes
  get '/embed', to: 'public_form#embed', as: 'embed_js'
  get '/f/:id', to: 'public_form#show', as: 'public_form'
  get '/f/:id/embed', to: 'public_form#show', defaults: { embed: true }, as: 'public_form_embed'
  post '/f/:id', to: 'public_form#submit', defaults: { format: :json }

  # result endpoint
  get '/r/:id', to: 'result#show', as: 'result'

  # subscriptions
  resources :subscriptions, only: [:index] do
    collection do
      get '/confirm/:plan', to: 'subscriptions#confirm', as: 'confirm'
    end
  end

  namespace :stripe, path: '/subscription' do
    post '/', to: 'subscription#create', as: 'create_subscription'
    put '/', to: 'subscription#update', as: 'update_subscription'
    delete '/', to: 'subscription#destroy', as: 'destroy_subscription'
    post '/webhook', to: 'subscription#webhook', as: 'subscription_webhook'
  end

  # pages
  get '/contact', to: 'contact#index', as: 'contact'

  # catch every other request and send it to our react app
  get '*anything', to: 'dashboard#index',
    constraints: lambda { |req|
      # exclude XHR requests
      return false if req.xhr?

      # exclude non-html requests
      return false unless req.format.html?

      # exclude any engine routes manually (e.g. sidekiq)
      req.path.exclude?('/sidekiq')
    }

  authenticated :user do
    root to: 'dashboard#index', as: 'dashboard'
  end

  root 'welcome#index'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index; end
end

app/views/welcome/_benefits.html.erb
<section class="section formsling-hero-image">
  <div class="container">
    <div class="columns">
      <div class="column is-4 has-text-white">
        <h4 class="title is-3 has-text-white">The Benefits of Embedded Forms</h4>
        <div class="content">
          <p>Pellentesque dictum purus leo, et placerat turpis porta gravida. In cursus diam id ipsum
            vulputate, ut
            venenatis eros porta. Aenean fringilla a nisi ac viverra.</p>
          <p>Curabitur sagittis sit amet quam at rhoncus. Ut sed consequat ex, sed consequat ipsum.
            Pellentesque nec
            nisi justo.</p>
        </div>
        <a class="button has-text-weight-bold formsling-button is-success">Get Started</a>
      </div>
      <div class="column is-8">
        <figure class="image">
          <%= image_tag asset_pack_path('media/images/checklist.svg'), alt: "Benefits illustration" %>
        </figure>
      </div>
    </div>
  </div>
</section>

app/views/welcome/_faq.html.erb
<section class="section formsling-background-light">
  <div class="container has-white-text">
    <div class="columns formsling-space-bottom">
      <div class="column is-8 is-offset-2">
        <div class="formsling-section-content has-text-centered">
          <h3 class="title">Frequently Asked Questions</h3>
        </div>
      </div>
    </div>
      <%= render partial:"welcome/faq_question",
        locals: {
          question: "How do I keep my subscription active after my free 30 day trial?",
          answer: "Throughout your trial, you can enter a payment method at any time by visiting your Manage Account page. When your trial ends, we'll bill your provided payment method automatically and your standard monthly subscription will begin."
      }%>
      <%= render partial:"welcome/faq_question",
        locals: {
          question: "What happens when my trial ends?",
          answer: "If you haven't provided a payment method, and your trial ends, your subscription may be canceled. If that happens you can start your standard subscription by visiting your Manage Account page."
      }%>
      <%= render partial:"welcome/faq_question",
        locals: {
          question: "What happens when my subscription is cancelled?",
          answer: "While canceled, your forms will continue functioning as normal, but you'll need to start a new subscription to edit them and reveal their results."
      }%>
      <%= render partial:"welcome/faq_question",
        locals: {
          question: "How do I cancel my subscription?",
          answer: "Visit your Manage Account page to find the option to cancel your subscription."
      }%>
  </div>
</section>

app/views/welcome/_faq_question.html.erb
<div class="column is-8 is-offset-2 has-text-centered">
  <h5 class="title has-text-weight-bold is-5">
    <i class="fad fa-check"></i>
    <%= question %>
  </h5>
  <div class="content">
    <p><%= answer %></p>
  </div>
</div>

app/views/welcome/_feature_card.html.erb
<div class="column is-one-third">
  <article class="card formsling-feature-card">
    <div class="card-content">
      <figure class="image is-159x159">
        <%= image_tag asset_pack_path("media/images/#{imageName}"), alt: imageAlt, width: "145", height: "159" %>
      </figure>

      <div class="media-content has-text-centered">
        <h3 class="title is-5 has-text-weight-bold">
          <a href="/" class="has-text-dark" title="">
            <%= title %>
          </a>
        </h3>
        <p class="is-size-6">
          <%= body %>
        </p>
      </div>
    </div>
  </article>
</div>

app/views/welcome/_features.html.erb
<section class="section formsling-features-cards">
  <div class="container">
    <div class="columns">
      <div class="column is-8-desktop is-offset-2-desktop">
        <div class="formsling-section-content has-text-centered">
          <h3 class="title has-text-dark">How to Get Started</h3>
          <p class="content has-text-grey is-size-5">
            <%= link_to 'Sign Up', new_user_registration_path %> for your free 30 day trial to see
            just how easy it is to create your own forms.
          </p>
        </div>
      </div>
    </div>
    <div class="columns">
      <%= render partial:"welcome/feature_card",
        locals: {
          imageName: "cons-pros.svg",
          imageAlt: "Build Icon",
          title: "Build",
          body: "Build your form using our easy to use form builder."
      }%>
      <%= render partial:"welcome/feature_card",
        locals: {
          imageName: "agile.svg",
          imageAlt: "Embed Icon",
          title: "Embed",
          body: "Embed your forms into your website or app for people to use."
      }%>
      <%= render partial:"welcome/feature_card",
        locals: {
          imageName: "planning.svg",
          imageAlt: "Collect Icon",
          title: "Collect",
          body: "Check your email or dashboard to see your form results."
      }%>
    </div>
  </div>
</section>

app/views/welcome/_hero.html.erb
<section class="hero formsling-main-hero">
  <div class="hero-head">
    <nav class="navbar container formsling-main-nav" role="navigation" aria-label="main navigation">
      <%= render 'layouts/navbar_brand' %>
      <%= render 'layouts/navbar_menu' %>
    </nav>
  </div>

  <div class="hero-body container">
    <div class="columns">
      <div class="column left is-5-desktop">
        <h1 class="title is-size-2-mobile is-1 is-spaced has-text-white">
          Create forms in seconds!
        </h1>
        <h2 class="subtitle is-5 has-text-white">
          Use FormSling to create forms and host them on your own website with no coding necessary.
        </h2>
        <div class="buttons">
          <%= link_to('Get Started Now', new_user_registration_path,
              class: "formsling-button button has-text-weight-bold is-info") %>
        </div>
      </div>
      <div class="column right is-5-desktop is-offset-1-desktop">
        <%= image_tag asset_pack_path('media/images/formsling-hero.png'), class: "formsling-main-hero--image", alt: "FormSling Screenshot" %>
      </div>
    </div>
  </div>
</section>

app/views/welcome/_pricing.html.erb
<section class="section formsling-pricing-section">
  <div class="container">
    <div class="columns formsling-space-bottom">
      <div class="column is-8 is-offset-2">
        <div class="formsling-section-content has-text-centered formsling-space-bottom">
          <h3 class="title has-text-dark">Pricing Tailored for You</h3>
          <p class="content has-text-grey has-text-weight-light is-size-5">
            Capitalize on low hanging fruit to identify a ballpark value added activity to beta test.
            Override the digital divide with additional clickthroughs.
          </p>
        </div>
      </div>
    </div>
    <div class="columns formsling-center-items formsling-space-around">
      <div class="column formsling-price-card has-text-centered">
        <h4 class="title is-1 has-text-dark has-text-weight-bold">Free</h4>
        <h5 class="subtitle has-text-weight-bold formsling-orange">30 Day Trial</h5>
        <ul class="has-text-weight-light has-text-dark is-size-6">
          <li class="plan-item">Unlimited Forms</li>
          <li class="plan-item">Unlimited Submissions</li>
          <li class="plan-item">Unlimited Shared Forms</li>
          <li class="plan-item">Unlimited Embedded Forms</li>
          <li class="plan-item">Spam Protection</li>
        </ul>
        <%= link_to('Get Started', new_user_registration_path,
            class: "button has-text-weight-bold formsling-orange is-rounded is-outlined") %>
      </div>
      <div class="column formsling-price-card has-text-centered formsling-active">
        <h4 class="title is-1 has-text-dark has-text-weight-bold"><span
            class="formsling-align-super is-size-2">$</span>10<span class="is-size-7">/month</span></h4>
        <h5 class="subtitle has-text-link has-text-weight-bold">Standard</h5>
        <ul class="has-text-weight-light has-text-dark is-size-6">
          <li class="plan-item">Unlimited Forms</li>
          <li class="plan-item">Unlimited Submissions</li>
          <li class="plan-item">Unlimited Shared Forms</li>
          <li class="plan-item">Unlimited Embedded Forms</li>
          <li class="plan-item">Spam Protection</li>

        </ul>
        <%= link_to('Buy Now', new_user_registration_path,
            class: "button has-text-weight-bold is-link is-rounded is-outlined") %>
      </div>
      <div class="column formsling-price-card has-text-centered">
        <h4 class="title is-1 has-text-dark has-text-weight-bold"><span
            class="formsling-align-super is-size-2">$</span>25<span class="is-size-7">/month</span></h4>
        <h5 class="subtitle formsling-purple has-text-weight-bold formsling-orange">Advanced</h5>
        <ul class="has-text-weight-light has-text-dark is-size-6">
          <li class="plan-item">Unlimited Forms</li>
          <li class="plan-item">Unlimited Submissions</li>
          <li class="plan-item">Unlimited Shared Forms</li>
          <li class="plan-item">Unlimited Embedded Forms</li>
          <li class="plan-item">Spam Protection</li>
          <li class="plan-item">Custom Styling</li>
          <li class="plan-item">Advanced Analytics</li>
        </ul>
        <button class="button has-text-weight-bold formsling-purple is-rounded is-outlined" disabled>Coming Soon</button>
      </div>
    </div>
  </div>
</section>

app/views/welcome/contact.html.erb
<% set_meta_tags(
  title: 'Contact',
  canonical: contact_url,
  description: "Sends us a quick message using our contact form.",
) %>

<section class="section has-text-centered has-margin-bottom-20">
  <div class="notification is-info is-inline">
    This contact form is actually a published form created within the platform.
  </div>
</section>

<script type="text/javascript" src="<%= embed_url %>"></script>
<a class="formsling-form-widget" href="<%= public_form_url(Form.first.id) %>">My first form</a>

<style>
  .formsling-iframe {width: 100%;}
</style>

app/views/welcome/index.html.erb
<% set_meta_tags(
  title: 'A Platform for Building and Publishing Web Forms',
  canonical: root_url,
  description: "FormSling is a platform for building and publishing web forms that allows you to create, share, and embed forms without any server infrastructure.",
) %>

<div class="welcome">
  <%= render 'hero' %>

  <a name="features"></a>
  <%= render 'features' %>

  <%= render 'benefits' %>

  <a name="pricing"></a>
  <%= render 'pricing' %>

  <a name="faq"></a>
  <%= render 'faq' %>
</div>

<footer class="footer">
  <div class="container">
    <div class="columns formsling-footer">
      <div class="column is-5 is-marginless has-text-centered-mobile content has-text-grey">
        <p>Copyright &copy; <%= Time.now.year %> FormSling. All rights reserved.</p>
      </div>
      <div class="column is-7">
        <ul class="columns formsling-bottom-links is-mobile is-multiline is-marginless">
          <li class="formsling-bottom-link">
            <%= link_to 'Contact Us', contact_path %>
          </li>
          <% unless user_signed_in? %>
            <li class="formsling-bottom-link">
              <%= link_to('Sign Up', new_user_registration_path) %>
            </li>
          <% end %>
          <li class="formsling-bottom-link">
            <% if user_signed_in? %>
              <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
            <% else %>
              <%= link_to('Sign In', new_user_session_path) %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>